# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/MildEye',
                'doc_host': 'https://mildhorton.github.io',
                'git_url': 'https://github.com/mildhorton/MildEye',
                'lib_path': 'MildEye'},
  'syms': {'MildEye.core': {'MildEye.core.foo': ('core.html#foo', 'MildEye/core.py')}}}
